# Copyright (C) 2026 Cross contributors
# SPDX-License-Identifier: GPL-3.0-or-later

# Compiles SOURCE at -O2 for ARCH and fails when an instruction inside a loop
# (from a local label to a later branch back to it), or anywhere in one of the
# FLAT functions, addresses the stack frame.
foreach(required CC SOURCE OUTPUT ARCH TARGET_FLAGS)
    if(NOT DEFINED ${required} OR "${${required}}" STREQUAL "")
        message(FATAL_ERROR "${required} must be defined")
    endif()
endforeach()
if(ARCH STREQUAL "x86_64")
    set(frame "\\(%r[sb]p\\)")
elseif(ARCH STREQUAL "mips")
    set(frame "\\(\\$(sp|fp)\\)")
else()
    message(FATAL_ERROR "unknown ARCH '${ARCH}'")
endif()

execute_process(COMMAND "${CC}" ${TARGET_FLAGS} -O2 -S "${SOURCE}"
                        -o "${OUTPUT}.s"
    RESULT_VARIABLE status OUTPUT_VARIABLE out ERROR_VARIABLE err)
if(NOT status EQUAL 0)
    message(FATAL_ERROR "compilation failed\n${out}\n${err}")
endif()

file(STRINGS "${OUTPUT}.s" lines)
set(labels "")
set(index 0)
set(loops 0)
set(function "")
set(flat_seen "")
foreach(line IN LISTS lines)
    if(line MATCHES "^([A-Za-z_][A-Za-z0-9_$]*):")
        set(function "${CMAKE_MATCH_1}")
        if(function IN_LIST FLAT)
            list(APPEND flat_seen "${function}")
        endif()
    elseif(line MATCHES "^(\\.L[.A-Za-z0-9_$]*):")
        set(label_${CMAKE_MATCH_1} ${index})
        list(APPEND labels "${CMAKE_MATCH_1}")
    elseif(line MATCHES "^[ \t]+[a-z]")
        if(function IN_LIST FLAT AND line MATCHES "${frame}")
            message(FATAL_ERROR
                "${function} accesses the frame: ${line}\nsee ${OUTPUT}.s")
        endif()
        foreach(label IN LISTS labels)
            string(REPLACE "." "\\." pattern "${label}")
            if(NOT line MATCHES "[\t ,]${pattern}$")
                continue()
            endif()
            math(EXPR loops "${loops} + 1")
            set(body ${label_${label}})
            while(body LESS index)
                list(GET lines ${body} candidate)
                if(candidate MATCHES "${frame}")
                    message(FATAL_ERROR
                        "loop at ${label} accesses the frame: ${candidate}\n"
                        "see ${OUTPUT}.s")
                endif()
                math(EXPR body "${body} + 1")
            endwhile()
        endforeach()
    endif()
    math(EXPR index "${index} + 1")
endforeach()
if(loops EQUAL 0)
    message(FATAL_ERROR "no loop found in ${OUTPUT}.s")
endif()
foreach(name IN LISTS FLAT)
    if(NOT name IN_LIST flat_seen)
        message(FATAL_ERROR "function ${name} not found in ${OUTPUT}.s")
    endif()
endforeach()
