# Copyright (C) 2026 Cross contributors
# SPDX-License-Identifier: GPL-3.0-or-later

foreach(required CC HOST_CXX SOURCE DRIVER OUTPUT)
    if(NOT DEFINED ${required} OR "${${required}}" STREQUAL "")
        message(FATAL_ERROR "${required} must name a path")
    endif()
endforeach()
if(WIN32)
    set(ABI ms_abi)
else()
    set(ABI sysv_abi)
endif()
foreach(level O0 O1 O2 O3 Os Oz)
    foreach(mode normal noeval)
        set(flags -${level} -DTEST_WIDE -mabi=${ABI})
        if(mode STREQUAL noeval)
            list(APPEND flags -fno-eval-calls)
        endif()
        set(stem "${OUTPUT}-${level}-${mode}")
        execute_process(COMMAND "${CC}" ${flags} -c "${SOURCE}" -o "${stem}.o"
            RESULT_VARIABLE s OUTPUT_VARIABLE out ERROR_VARIABLE err)
        if(NOT s EQUAL 0)
            message(FATAL_ERROR "required constants compile failed (${level}/${mode})\n${out}\n${err}")
        endif()
        execute_process(COMMAND "${HOST_CXX}" "${DRIVER}" "${stem}.o" -o "${stem}.exe"
            RESULT_VARIABLE s OUTPUT_VARIABLE out ERROR_VARIABLE err)
        if(NOT s EQUAL 0)
            message(FATAL_ERROR "required constants link failed (${level}/${mode})\n${out}\n${err}")
        endif()
        execute_process(COMMAND "${stem}.exe" RESULT_VARIABLE s)
        if(NOT s EQUAL 0)
            message(FATAL_ERROR "required constants runtime mismatch (${level}/${mode}): ${s}")
        endif()
    endforeach()
endforeach()

execute_process(COMMAND "${CC}" -S -O0 -fno-eval-calls -DTEST_WIDE "${SOURCE}" -o "${OUTPUT}.s"
    RESULT_VARIABLE s OUTPUT_VARIABLE out ERROR_VARIABLE err)
if(NOT s EQUAL 0)
    message(FATAL_ERROR "generic identity compile failed\n${out}\n${err}")
endif()
file(READ "${OUTPUT}.s" assembly)
string(REGEX MATCHALL "constant_identity::<[^\n]+>\":" definitions "${assembly}")
list(LENGTH definitions count)
if(NOT count EQUAL 1 OR NOT assembly MATCHES "constant_identity::<u32,4uptr>")
    message(FATAL_ERROR "equivalent generic values must share one normalized instance: ${definitions}")
endif()
