# Copyright (C) 2026 Cross contributors
# SPDX-License-Identifier: GPL-3.0-or-later

# Checks that the early exit of sw_fib runs without saves, restores, or stack
# adjustment, and that -fno-shrink-wrap keeps the prologue at entry.
foreach(required CC OUTPUT ARCH)
    if(NOT DEFINED ${required} OR "${${required}}" STREQUAL "")
        message(FATAL_ERROR "${required} must be defined")
    endif()
endforeach()

if(ARCH STREQUAL "x86_64")
    set(source "${CMAKE_CURRENT_LIST_DIR}/shrink_wrap.x")
    set(target_flags)
    set(branch "^\tj[a-ln-z][a-z]*\t")
    set(exit "^\tretq")
    set(frame "^\t(pushq|popq)\t|%rsp$|\\(%rsp\\)")
elseif(ARCH STREQUAL "mips")
    set(source "${CMAKE_CURRENT_LIST_DIR}/mips.x")
    set(target_flags -target mips-unknown-elf -march=vr4300 -mabi=o32)
    set(branch "^\tb(eq|ne|lez|gtz|ltz|gez)l?\t")
    set(exit "^\tjr\t\\$ra")
    set(frame "^\t[a-z].*\\$sp")
else()
    message(FATAL_ERROR "unknown ARCH '${ARCH}'")
endif()

# Splits sw_fib into the instructions before its first conditional branch
# and the block that branch reaches.
function(early_exit assembly entry_out exit_out)
    string(FIND "${assembly}" "\nsw_fib:\n" start)
    if(start EQUAL -1)
        message(FATAL_ERROR "sw_fib is missing from the ${ARCH} assembly")
    endif()
    string(SUBSTRING "${assembly}" ${start} -1 rest)
    string(REPLACE ";" "," rest "${rest}")
    string(REPLACE "\n" ";" lines "${rest}")
    set(entry)
    set(label)
    foreach(line IN LISTS lines)
        if(line MATCHES "${branch}")
            string(REGEX REPLACE ".*[\t,]([^\t,]+)$" "\\1" label "${line}")
            break()
        endif()
        list(APPEND entry "${line}")
    endforeach()
    if(NOT label)
        message(FATAL_ERROR "sw_fib has no conditional branch")
    endif()
    set(block)
    set(inside FALSE)
    foreach(line IN LISTS lines)
        if(line STREQUAL "${label}:")
            set(inside TRUE)
        elseif(inside)
            list(APPEND block "${line}")
            if(line MATCHES "${exit}")
                break()
            endif()
        endif()
    endforeach()
    set(${entry_out} "${entry}" PARENT_SCOPE)
    set(${exit_out} "${block}" PARENT_SCOPE)
endfunction()

function(uses_frame lines result)
    set(found FALSE)
    foreach(line IN LISTS lines)
        if(line MATCHES "${frame}")
            set(found TRUE)
        endif()
    endforeach()
    set(${result} ${found} PARENT_SCOPE)
endfunction()

foreach(mode shrink-wrap no-shrink-wrap)
    execute_process(COMMAND "${CC}" ${target_flags} -O2 -f${mode} -S "${source}"
        -o "${OUTPUT}-${mode}.s" RESULT_VARIABLE status ERROR_VARIABLE errors)
    if(NOT status EQUAL 0)
        message(FATAL_ERROR "${ARCH} -f${mode} assembly failed\n${errors}")
    endif()
    file(READ "${OUTPUT}-${mode}.s" assembly)
    early_exit("${assembly}" entry block)
    uses_frame("${entry}" entry_frame)
    uses_frame("${block}" exit_frame)
    if(mode STREQUAL shrink-wrap AND (entry_frame OR exit_frame))
        message(FATAL_ERROR "${ARCH} early exit saves or restores:\n${entry}\n${block}")
    elseif(mode STREQUAL no-shrink-wrap AND NOT entry_frame)
        message(FATAL_ERROR "${ARCH} -fno-shrink-wrap moved the prologue:\n${entry}")
    endif()
endforeach()
