# Copyright (C) 2026 Cross contributors
# SPDX-License-Identifier: GPL-3.0-or-later
set(base "${OUTPUT}")
set(SOURCE "${CMAKE_CURRENT_LIST_DIR}/runtime.x")
set(STARTUP "${CMAKE_CURRENT_LIST_DIR}/mips_startup.s")
set(EXPECTED P)
foreach(level O0 O2 O3 Oz)
  foreach(private private-abi no-private-abi)
    set(OUTPUT "${base}-${level}-${private}")
    set(CC_FLAGS -${level} -f${private})
    include("${CMAKE_CURRENT_LIST_DIR}/../../language/semantics/mips.cmake")
    set(EXTRA_FLAGS "-${level} -f${private}")
    set(LINKER "${CMAKE_CURRENT_LIST_DIR}/../../target/mips/bare-n64.ld")
    foreach(N64_ENDIAN big little)
        set(OUTPUT "${base}-${level}-${private}-n64-${N64_ENDIAN}")
        include("${CMAKE_CURRENT_LIST_DIR}/../../target/mips/n64_runtime.cmake")
    endforeach()
  endforeach()
endforeach()
