# Copyright (C) 2026 Cross contributors
# SPDX-License-Identifier: GPL-3.0-or-later

set(base "${OUTPUT}")
set(STARTUP "${CMAKE_CURRENT_LIST_DIR}/mips_startup.s")
set(EXPECTED "1")
foreach(mode enabled disabled)
  foreach(fp omit-frame-pointer no-omit-frame-pointer)
    set(OUTPUT "${base}-${mode}-${fp}")
    if(mode STREQUAL enabled)
        set(CC_FLAGS -felide-noreturn-saves)
    else()
        set(CC_FLAGS -fno-elide-noreturn-saves)
    endif()
    list(APPEND CC_FLAGS -f${fp})
    include("${CMAKE_CURRENT_LIST_DIR}/../../language/semantics/mips.cmake")
    foreach(cpu vr4300 r3000)
        execute_process(COMMAND "${CC}" -target mips-unknown-elf -march=${cpu}
            -mabi=o32 -O2 ${CC_FLAGS} -S "${SOURCE}" -o "${OUTPUT}-${cpu}.s"
            RESULT_VARIABLE status)
        if(NOT status EQUAL 0)
            message(FATAL_ERROR "MIPS noreturn assembly failed")
        endif()
        file(READ "${OUTPUT}-${cpu}.s" assembly)
        set(save "s[wd][\t ]+[$]s[0-7],")
        if(mode STREQUAL enabled AND assembly MATCHES "${save}")
            message(FATAL_ERROR "eligible MIPS noreturn retained incoming saves")
        elseif(mode STREQUAL disabled AND NOT assembly MATCHES "${save}")
            message(FATAL_ERROR "disabled MIPS noreturn lost incoming saves")
        endif()
        set(frame_save "s[wd][\t ]+[$](ra|fp),")
        if(mode STREQUAL enabled AND assembly MATCHES "${frame_save}")
            message(FATAL_ERROR "eligible MIPS noreturn retained incoming RA/FP")
        elseif(mode STREQUAL disabled AND NOT assembly MATCHES "s[wd][\t ]+[$]ra,")
            message(FATAL_ERROR "disabled MIPS noreturn lost incoming RA")
        endif()
        if(fp STREQUAL no-omit-frame-pointer AND
           NOT assembly MATCHES "move[\t ]+[$]fp,[$]sp")
            message(FATAL_ERROR "MIPS working frame pointer was removed")
        endif()
    endforeach()
  endforeach()
endforeach()
