# Copyright (C) 2026 Cross contributors
# SPDX-License-Identifier: GPL-3.0-or-later
foreach(required CC SOURCE OUTPUT)
    if(NOT DEFINED ${required} OR "${${required}}" STREQUAL "")
        message(FATAL_ERROR "${required} must name a value")
    endif()
endforeach()
foreach(target native mips mipsel mips64 mips64el)
    set(target_flags)
    if(target STREQUAL mips OR target STREQUAL mipsel)
        set(target_flags -target "${target}-unknown-elf" -march=vr4300 -mabi=o32)
    elseif(target MATCHES "^mips64")
        set(target_flags -target "${target}-unknown-elf" -march=mips64 -mabi=n64)
    endif()
    foreach(level O0 O2)
        foreach(mode RANGE 0 26)
            set(expected "fixed array bound must be a positive integer representable in 32 bits")
            if(mode EQUAL 5 OR mode EQUAL 17 OR mode EQUAL 18 OR mode EQUAL 24)
                set(expected "runtime local or parameter is not a translation-time value")
            elseif(mode EQUAL 7)
                set(expected "redeclared with a different type")
            elseif(mode EQUAL 9)
                set(expected "fixed-vector lane index is out of range")
            elseif(mode EQUAL 11)
                set(expected "required expression is not an integer translation-time value")
            elseif(mode EQUAL 12)
                set(expected "string initializer")
            elseif(mode EQUAL 13)
                set(expected "initializer.*(outside|range|excess|exceed)")
            elseif(mode EQUAL 15 OR mode EQUAL 23)
                set(expected "unresolved name 'later'")
            elseif(mode EQUAL 16 OR mode EQUAL 26)
                set(expected "unresolved name 'hidden'")
            elseif(mode EQUAL 25)
                set(expected "unresolved name 'value'")
            elseif(mode GREATER_EQUAL 19 AND mode LESS_EQUAL 21)
                set(expected "fixed array bound must be a positive integer translation-time value")
            elseif(mode EQUAL 22)
                set(expected "integer literal")
            endif()
            execute_process(COMMAND "${CC}" -S "-${level}" -fno-eval-calls
                ${target_flags} "-DMODE=${mode}" "${SOURCE}"
                -o "${OUTPUT}-${target}-${level}-${mode}.s"
                RESULT_VARIABLE status OUTPUT_VARIABLE out ERROR_VARIABLE err)
            if(status EQUAL 0 OR NOT err MATCHES "${expected}")
                message(FATAL_ERROR "${target}/${level}/${mode}: expected '${expected}'\n${out}\n${err}")
            endif()
        endforeach()
    endforeach()
endforeach()
