# Copyright (C) 2026 Cross contributors
# SPDX-License-Identifier: GPL-3.0-or-later

if(NOT DEFINED CC OR NOT DEFINED SOURCE OR NOT DEFINED OUTPUT)
    message(FATAL_ERROR "CC, SOURCE, and OUTPUT are required")
endif()
set(directory "${OUTPUT}.cases")
file(MAKE_DIRECTORY "${directory}")

foreach(target mips-unknown-linux-gnu mipsel-unknown-linux-gnu
               mips64-unknown-linux-gnu mips64el-unknown-linux-gnu)
    execute_process(COMMAND "${CC}" -S -target "${target}" "${SOURCE}"
        -o "${directory}/${target}.s"
        RESULT_VARIABLE status OUTPUT_VARIABLE out ERROR_VARIABLE err)
    if(NOT status EQUAL 0)
        message(FATAL_ERROR "${target} meta object evaluation failed\n${out}\n${err}")
    endif()
    file(READ "${directory}/${target}.s" assembly)
    if(NOT assembly MATCHES "pointer_objects_checked:\n[^\n]*[.](word|dword|long|quad) 1" OR
       NOT assembly MATCHES "initialized_objects_checked:\n[^\n]*[.](word|dword|long|quad) 1" OR
       NOT assembly MATCHES "conditional_object_checked:\n[^\n]*[.](word|dword|long|quad) 1")
        message(FATAL_ERROR "${target} pointer object evaluation produced an incorrect value")
    endif()
endforeach()

get_filename_component(source_directory "${SOURCE}" DIRECTORY)
foreach(target mips-unknown-linux-gnu mipsel-unknown-linux-gnu
               mips64-unknown-linux-gnu mips64el-unknown-linux-gnu)
    execute_process(COMMAND "${CC}" -S -DMETA_COMPILE_ONLY=1 -target "${target}" "${source_directory}/meta_vectors.x"
        -o "${directory}/vectors-${target}.s"
        RESULT_VARIABLE status OUTPUT_VARIABLE out ERROR_VARIABLE err)
    if(NOT status EQUAL 0)
        message(FATAL_ERROR "${target} vector evaluation failed\n${out}\n${err}")
    endif()
    file(READ "${directory}/vectors-${target}.s" assembly)
    if(NOT assembly MATCHES "vector_unary_checked:\n[^\n]*[.](word|dword|long|quad) 1")
        message(FATAL_ERROR "${target} vector unary evaluation produced an incorrect value")
    endif()
endforeach()

foreach(case lifetime_scalar lifetime_array lifetime_record frozen_loaded opaque_byte
             opaque_scalar opaque_freeze partial_pointer pointer_alias pointer_unassigned
             pointer_compound aggregate_escape enum_alias enum_write_alias
             initializer_duplicate initializer_range initializer_excess vla_zero vla_range
             vector_shape vector_operator vector_divzero)
    set(prelude "struct box { u32 *value; };\nstruct record { u32 word; };\n")
    if(case STREQUAL lifetime_scalar)
        set(body "u32 *p = 0; { u32 value = 4u32; p = &value; } return *p;")
        set(expected "outside its lifetime")
    elseif(case STREQUAL lifetime_array)
        set(body "u32 *p = 0; { u32 value[2] = { 3u32, 4u32 }; p = value; } return p[0];")
        set(expected "outside its lifetime")
    elseif(case STREQUAL lifetime_record)
        set(body "struct box value; { u32 local = 4u32; value.value = &local; } return *value.value;")
        set(expected "outside its lifetime")
    elseif(case STREQUAL frozen_loaded)
        set(body "$::meta::buffer bytes = $::meta::alloc(4u32); u32 *p = (u32 *)$::meta::data(bytes); *p = 7u32; struct box value = { p }; $::meta::bytes frozen = $::meta::freeze(bytes, 4u32); return *value.value;")
        set(expected "after freeze")
    elseif(case STREQUAL opaque_byte OR case STREQUAL opaque_scalar)
        set(body "u32 local = 3u32; u32 *pointer = &local; return ((u8 *)&pointer)[0];")
        if(case STREQUAL opaque_scalar)
            set(body "u32 local = 3u32; u32 *pointer = &local; return ((uptr *)&pointer)[0];")
        endif()
        set(expected "opaque translation-time pointer representation")
    elseif(case STREQUAL partial_pointer)
        set(body "u32 local = 3u32; u32 *pointer = &local; ((u8 *)&pointer)[0] = 0u8; return *pointer;")
        set(expected "unassigned buffer byte")
    elseif(case STREQUAL opaque_freeze)
        set(body "u32 local = 3u32; $::meta::buffer bytes = $::meta::alloc(sizeof(u32 *)); *((u32 **)$::meta::data(bytes)) = &local; $::meta::bytes frozen = $::meta::freeze(bytes, sizeof(u32 *)); return 0;")
        set(expected "opaque.*pointer")
    elseif(case STREQUAL pointer_unassigned)
        set(body "$::meta::buffer bytes = $::meta::alloc(sizeof(u32 *)); return (bool)*((u32 **)$::meta::data(bytes));")
        set(expected "unassigned buffer byte")
    elseif(case STREQUAL pointer_compound)
        set(body "u32 local[2] = { 3u32, 4u32 }; struct box value = { local }; value.value *= 1u32; return *value.value;")
        set(expected "pointer compound assignment")
    elseif(case STREQUAL pointer_alias)
        set(body "u32 local = 3u32; u32 *pointer = &local; f32 **alias = (f32 **)&pointer; return (bool)*alias;")
        set(expected "effective type")
    elseif(case STREQUAL aggregate_escape)
        set(prelude "struct box { u32 *value; };\n[[eval_only]] static struct box make() { u32 local = 3u32; struct box value = { &local }; return value; }\n")
        set(body "")
        set(expected "pointer cannot escape|outside its lifetime")
    elseif(case STREQUAL enum_alias OR case STREQUAL enum_write_alias)
        string(APPEND prelude "enum first [[underlying(u32)]] { A = 3u32 }; enum second [[underlying(u32)]] { B = 4u32 };\n")
        set(body "$::meta::buffer bytes = $::meta::alloc(sizeof(enum first)); enum first *a = (enum first *)$::meta::data(bytes); *a = A; enum second *b = (enum second *)a; return (uptr)*b;")
        if(case STREQUAL enum_write_alias)
            set(body "$::meta::buffer bytes = $::meta::alloc(sizeof(enum first)); enum first *a = (enum first *)$::meta::data(bytes); *a = A; *((enum second *)a) = B; return 0;")
        endif()
        set(expected "effective type")
    elseif(case STREQUAL initializer_duplicate)
        set(body "u32 value[2] = { [1] = 3u32, [1] = 4u32 }; return value[1];")
        set(expected "duplicate destination")
    elseif(case STREQUAL initializer_range)
        set(body "u32 value[2] = { [2] = 3u32 }; return value[0];")
        set(expected "out of range")
    elseif(case STREQUAL vla_zero OR case STREQUAL vla_range)
        set(body "uptr count = 0uptr; u32 value[count]; return sizeof(value);")
        set(expected "positive|nonzero")
        if(case STREQUAL vla_range)
            set(body "uptr count = 2uptr; u32 value[count] = { [2] = 3u32 }; return value[0];")
            set(expected "out of range")
        endif()
    elseif(case MATCHES "^vector_")
        string(APPEND prelude "typedef u32 v4 [[ext_vector_type(4)]]; typedef u32 v2 [[ext_vector_type(2)]]; typedef f32 f4 [[ext_vector_type(4)]];\n")
        if(case STREQUAL vector_shape)
            set(body "v4 left = 1u32; v2 right = 2u32; return (left + right)[0];")
            set(expected "vector.*operator|vector.*type|incompatible")
        elseif(case STREQUAL vector_operator)
            set(body "f4 left = 1.0f32; return (left & left)[0];")
            set(expected "vector.*operator|vector.*type|incompatible")
        else()
            set(body "v4 left = 1u32; v4 right = 1u32; right[2] = 0u32; return (left / right)[0];")
            set(expected "division by zero")
        endif()
    else()
        set(body "struct record value = { 1u32, 2u32 }; return value.word;")
        set(expected "excess entry")
    endif()
    if(case STREQUAL aggregate_escape)
        set(source "${prelude}global struct box escaped = make();\n")
    else()
        set(source "${prelude}[[eval_only]] static uptr bad() { ${body} }\nglobal uptr result = bad();\n")
    endif()
    set(input "${directory}/${case}.x")
    file(WRITE "${input}" "${source}")
    foreach(target x86_64-unknown-linux-gnu mips-unknown-linux-gnu mipsel-unknown-linux-gnu
                   mips64-unknown-linux-gnu mips64el-unknown-linux-gnu)
        execute_process(COMMAND "${CC}" -S -target "${target}" "${input}"
            -o "${directory}/${case}-${target}.s"
            RESULT_VARIABLE status OUTPUT_VARIABLE out ERROR_VARIABLE err)
        if(status EQUAL 0 OR NOT err MATCHES "${expected}" OR
           NOT err MATCHES "${case}.x:[0-9]+:[0-9]+: error:")
            message(FATAL_ERROR "${case}/${target} was not diagnosed correctly\n${out}\n${err}")
        endif()
    endforeach()
endforeach()
