# Copyright (C) 2026 Cross contributors
# SPDX-License-Identifier: GPL-3.0-or-later
foreach(required CPP CC SOURCE OUTPUT)
    if(NOT DEFINED ${required})
        message(FATAL_ERROR "${required} must be set")
    endif()
endforeach()
set(flags -DCOMMAND_PRESENT=23 -DCOMMAND_DISABLED -UCOMMAND_DISABLED)
foreach(tool CPP CC)
    execute_process(COMMAND "${${tool}}" -E ${flags} "${SOURCE}" -o "${OUTPUT}.${tool}.x"
        RESULT_VARIABLE status OUTPUT_VARIABLE out ERROR_VARIABLE err)
    if(NOT status EQUAL 0)
        message(FATAL_ERROR "${tool} condition test failed\n${out}\n${err}")
    endif()
endforeach()
file(READ "${OUTPUT}.CPP.x" cpp)
file(READ "${OUTPUT}.CC.x" cc)
if(NOT cpp STREQUAL cc)
    message(FATAL_ERROR "standalone and integrated preprocessing disagree")
endif()
foreach(profile vr4300-o32 mips64-n64)
    execute_process(COMMAND "${CPP}" -mprofile=${profile} ${flags} "${SOURCE}"
        -o "${OUTPUT}.${profile}.x"
        RESULT_VARIABLE status OUTPUT_VARIABLE out ERROR_VARIABLE err)
    if(NOT status EQUAL 0)
        message(FATAL_ERROR "target-aware condition test failed: ${profile}\n${out}\n${err}")
    endif()
endforeach()
foreach(name correct_branch selected_elif continued_condition after_undef empty_expansion spliced_comment)
    if(NOT cpp MATCHES "global i32 ${name}")
        message(FATAL_ERROR "missing selected output: ${name}")
    endif()
endforeach()
execute_process(COMMAND "${CC}" -S ${flags} "${SOURCE}" -o "${OUTPUT}.s"
    RESULT_VARIABLE status OUTPUT_VARIABLE out ERROR_VARIABLE err)
if(NOT status EQUAL 0)
    message(FATAL_ERROR "selected Cross output failed to compile\n${out}\n${err}")
endif()

foreach(flag "-D$::target::abi=0" "-U$::target::abi")
    execute_process(COMMAND "${CPP}" "${flag}" "${SOURCE}" -o "${OUTPUT}.builtin.i"
        RESULT_VARIABLE status OUTPUT_VARIABLE out ERROR_VARIABLE err)
    if(status EQUAL 0 OR NOT err MATCHES "non-builtin macro name")
        message(FATAL_ERROR "command line changed a builtin macro\n${out}\n${err}")
    endif()
endforeach()

function(expect_error name source pattern)
    set(path "${OUTPUT}.${name}.x")
    file(WRITE "${path}" "${source}")
    execute_process(COMMAND "${CPP}" "${path}" -o "${path}.i"
        RESULT_VARIABLE status OUTPUT_VARIABLE out ERROR_VARIABLE err)
    if(status EQUAL 0 OR NOT err MATCHES "${pattern}")
        message(FATAL_ERROR "wrong diagnostic for ${name}: ${status}\n${out}\n${err}")
    endif()
    if(NOT err MATCHES "${name}\\.x:[0-9]+:[0-9]+: error:")
        message(FATAL_ERROR "missing original source position for ${name}\n${err}")
    endif()
endfunction()
expect_error(defined "#if defined(1)\n#endif\n" "defined requires a macro name")
expect_error(else "#if 1\n#else\n#else\n#endif\n" "#else after #else")
expect_error(elif "#if 1\n#else\n#elif 1\n#endif\n" "#elif after #else")
expect_error(unmatched "#elif 1\n" "unmatched #elif")
expect_error(unterminated "#if 1\n" "unterminated conditional")
expect_error(trailing "#if 1\n#endif extra\n" "unexpected tokens after #endif")
expect_error(empty "#if\n#endif\n" "expected integer expression")
expect_error(divzero "#if 1 / 0\n#endif\n" "division by zero")
expect_error(shift "#if 1 << 64\n#endif\n" "shift count")
expect_error(ternary "#if 1 ? 2 : 3\n#endif\n" "unexpected token")
expect_error(builtin "#undef $::target::abi\n" "non-builtin macro name")
expect_error(unknown "#iffoo 1\n" "unsupported preprocessing directive")
expect_error(require_false "#require 0\n" "#require condition is false")
expect_error(require_reason "#require 0, \"needed, now\"\n" "#require condition is false: needed, now")
expect_error(require_reason_macro "#define WHY \"expanded reason\"\n#require 0, WHY\n" "#require condition is false: expanded reason")
expect_error(require_invalid_reason "#require 0, \"one\" \"two\"\n" "#require reason must be one string literal")
expect_error(require_missing "#require , \"missing\"\n" "expected integer expression")
expect_error(require_nested "#require UNKNOWN(1, 2), \"nested\"\n" "unexpected token")
expect_error(require_feature "#require $::has_feature($::feature::not_a_real_feature)\n" "#require condition is false")

set(included "${OUTPUT}.included.x")
file(WRITE "${included}" "\n\n#if 1 / 0\n#endif\n")
file(WRITE "${OUTPUT}.include.x" "#include \"${included}\"\n")
execute_process(COMMAND "${CPP}" "${OUTPUT}.include.x" -o "${OUTPUT}.include.i"
    RESULT_VARIABLE status OUTPUT_VARIABLE out ERROR_VARIABLE err)
if(status EQUAL 0 OR NOT err MATCHES "included\\.x:3:1: error: division by zero")
    message(FATAL_ERROR "lost included-file diagnostic location\n${out}\n${err}")
endif()

file(WRITE "${OUTPUT}.require-included.x" "\n\n#require 0, \"from include\"\n")
file(WRITE "${OUTPUT}.require-include.x"
    "#include \"${OUTPUT}.require-included.x\"\n")
execute_process(COMMAND "${CPP}" "${OUTPUT}.require-include.x"
    -o "${OUTPUT}.require-include.i"
    RESULT_VARIABLE status OUTPUT_VARIABLE out ERROR_VARIABLE err)
if(status EQUAL 0 OR NOT err MATCHES
   "require-included\\.x:3:1: error: #require condition is false: from include")
    message(FATAL_ERROR "lost #require included-file location\n${out}\n${err}")
endif()
