# Copyright (C) 2026 Cross contributors
# SPDX-License-Identifier: GPL-3.0-or-later

foreach(required CC HOST_CXX SOURCE_DIR MODEL RUNNER OUTPUT)
    if(NOT DEFINED ${required})
        message(FATAL_ERROR "${required} must name a path")
    endif()
endforeach()
if(WIN32)
    set(host_abi ms_abi)
else()
    set(host_abi sysv_abi)
endif()

foreach(level O0 O2 O3 Os Oz)
    foreach(mode ordinary noeval custom custom-noalloc)
        set(flags "-mabi=${host_abi}" -${level} -DTEST_MACRO_RAW)
        if(mode STREQUAL noeval)
            list(APPEND flags -fno-eval-calls -fno-inline)
        elseif(mode MATCHES "^custom")
            set(flags "--model=${MODEL}" -mabi=odd_abi -DCUSTOM_MACRO_ABI
                "-DHOST_ABI=\"${host_abi}\"" -${level} -fno-eval-calls -fno-inline -DTEST_MACRO_RAW)
            if(mode STREQUAL custom-noalloc)
                list(APPEND flags -fno-register-allocation)
            endif()
        endif()
        set(stem "${OUTPUT}-${level}-${mode}")
        execute_process(COMMAND "${CC}" ${flags} -c "${SOURCE_DIR}/procedural_scalar.x" -o "${stem}.o"
            RESULT_VARIABLE status OUTPUT_VARIABLE out ERROR_VARIABLE err TIMEOUT 20)
        if(NOT status EQUAL 0)
            message(FATAL_ERROR "macro scalar compile failed ${level}/${mode}\n${out}\n${err}")
        endif()
        execute_process(COMMAND "${HOST_CXX}" -DCROSS_ENTRY=procedural_scalar_entry "${RUNNER}" "${stem}.o" -o "${stem}.exe"
            RESULT_VARIABLE status OUTPUT_VARIABLE out ERROR_VARIABLE err)
        if(NOT status EQUAL 0)
            message(FATAL_ERROR "macro runtime link failed ${level}/${mode}\n${out}\n${err}")
        endif()
        execute_process(COMMAND "${stem}.exe" RESULT_VARIABLE status)
        if(NOT status EQUAL 0)
            message(FATAL_ERROR "macro runtime mismatch ${level}/${mode}: ${status}")
        endif()
    endforeach()
endforeach()

foreach(profile test-profile test-option-profile)
    execute_process(COMMAND "${CC}" "--model=${MODEL}" "-mprofile=${profile}"
        -fno-eval-calls -S "${SOURCE_DIR}/procedural_scalar.x" -o "${OUTPUT}-${profile}.s"
        RESULT_VARIABLE status OUTPUT_VARIABLE out ERROR_VARIABLE err)
    if(NOT status EQUAL 0)
        message(FATAL_ERROR "macro custom profile compile failed ${profile}\n${out}\n${err}")
    endif()
endforeach()

foreach(target host mips mipsel mips64 mips64el)
    set(flags "-mabi=${host_abi}")
    if(target STREQUAL mips OR target STREQUAL mipsel)
        set(flags -target "${target}-unknown-elf" -march=r3000 -mabi=o32)
    elseif(target STREQUAL mips64 OR target STREQUAL mips64el)
        set(flags -target "${target}-unknown-elf" -march=mips64 -mabi=n64)
    endif()
    foreach(level O0 O2)
        execute_process(COMMAND "${CC}" ${flags} -${level} -fno-eval-calls -c
            "${SOURCE_DIR}/procedural_scalar.x" -o "${OUTPUT}-${target}-${level}.o"
            RESULT_VARIABLE status OUTPUT_VARIABLE out ERROR_VARIABLE err TIMEOUT 20)
        if(NOT status EQUAL 0)
            message(FATAL_ERROR "macro target compile failed ${target}/${level}\n${out}\n${err}")
        endif()
        foreach(case OVERFLOW SHIFT DIVIDE UNINITIALIZED CONST_WRITE INPUT_WRITE DUPLICATE
                     DEAD_UNKNOWN DEAD_TOKEN_CAST DEAD_TOKEN_ASSIGN TOKEN_CONDITION TOKEN_LAYOUT TOKEN_POINTER_LAYOUT TOKEN_ARITHMETIC
                     BAD_SPLICE BAD_CONCAT BAD_PARSE PARSE_ZERO PARSE_GROUP PARSE_LEX QUOTE_GROUP
                     BAD_RETURN BAD_BREAK STATIC VOLATILE LOOP_BUDGET TOKEN_BUDGET TOKEN_ESCAPE QUOTE_ESCAPE)
            if(case STREQUAL OVERFLOW)
                set(expected "signed overflow")
            elseif(case STREQUAL SHIFT)
                set(expected "invalid shift count")
            elseif(case STREQUAL DIVIDE)
                set(expected "division by zero")
            elseif(case STREQUAL UNINITIALIZED)
                set(expected "read of uninitialized")
            elseif(case STREQUAL CONST_WRITE OR case STREQUAL INPUT_WRITE)
                set(expected "cannot write an 'in' or const cell")
            elseif(case STREQUAL DUPLICATE)
                set(expected "declared more than once")
            elseif(case STREQUAL DEAD_UNKNOWN)
                set(expected "unresolved name")
            elseif(case STREQUAL DEAD_TOKEN_CAST)
                set(expected "unsupported conversion")
            elseif(case STREQUAL DEAD_TOKEN_ASSIGN)
                set(expected "incompatible assignment type")
            elseif(case STREQUAL TOKEN_CONDITION)
                set(expected "condition must be scalar")
            elseif(case STREQUAL TOKEN_LAYOUT OR case STREQUAL TOKEN_POINTER_LAYOUT)
                set(expected "layout query requires a runtime object type")
            elseif(case STREQUAL TOKEN_ARITHMETIC)
                set(expected "unsupported type")
            elseif(case STREQUAL BAD_SPLICE)
                set(expected "unquote requires a token value")
            elseif(case STREQUAL BAD_CONCAT)
                set(expected "concat requires token values")
            elseif(case STREQUAL BAD_PARSE)
                set(expected "parse requires a translation-time string")
            elseif(case STREQUAL PARSE_ZERO)
                set(expected "parse string contains a zero byte")
            elseif(case STREQUAL PARSE_GROUP OR case STREQUAL QUOTE_GROUP)
                set(expected "requires balanced token groups")
            elseif(case STREQUAL PARSE_LEX)
                set(expected "could not tokenize its string")
            elseif(case STREQUAL BAD_RETURN)
                set(expected "must return a token value")
            elseif(case STREQUAL BAD_BREAK)
                set(expected "no enclosing control statement")
            elseif(case STREQUAL STATIC OR case STREQUAL VOLATILE)
                set(expected "without runtime storage qualifiers")
            elseif(case STREQUAL LOOP_BUDGET)
                set(expected "instruction budget exceeded")
            elseif(case STREQUAL TOKEN_BUDGET)
                set(expected "token construction budget exceeded")
            elseif(case STREQUAL TOKEN_ESCAPE OR case STREQUAL QUOTE_ESCAPE)
                set(expected "only available in translation-time macro bodies")
            endif()
            execute_process(COMMAND "${CC}" ${flags} -${level} "-D${case}" -S
                "${SOURCE_DIR}/procedural_scalar_errors.x" -o "${OUTPUT}-error.s"
                RESULT_VARIABLE status OUTPUT_VARIABLE out ERROR_VARIABLE err TIMEOUT 20)
            if(status EQUAL 0 OR NOT err MATCHES "${expected}" OR
               NOT err MATCHES "procedural_scalar_errors\\.x:[0-9]+:[0-9]+")
                message(FATAL_ERROR "macro diagnostic ${target}/${level}/${case}\n${out}\n${err}")
            endif()
        endforeach()
        foreach(case QUOTED_CAPTURE COPIED_READONLY DUPLICATE_QUOTE)
            if(case STREQUAL QUOTED_CAPTURE)
                set(expected "has no value in this syntax context")
            elseif(case STREQUAL COPIED_READONLY)
                set(expected "cannot write an 'in' or const cell")
            else()
                set(expected "declared more than once")
            endif()
            execute_process(COMMAND "${CC}" ${flags} -${level} "-D${case}" -S
                "${SOURCE_DIR}/procedural_local_errors.x" -o "${OUTPUT}-local-error.s"
                RESULT_VARIABLE status OUTPUT_VARIABLE out ERROR_VARIABLE err TIMEOUT 20)
            if(status EQUAL 0 OR NOT err MATCHES "${expected}" OR
               NOT err MATCHES "procedural_local_errors\\.x:[0-9]+:[0-9]+")
                message(FATAL_ERROR "macro local diagnostic ${target}/${level}/${case}\n${out}\n${err}")
            endif()
        endforeach()
    endforeach()
endforeach()
