# Copyright (C) 2026 Cross contributors
# SPDX-License-Identifier: GPL-3.0-or-later
foreach(required CC SOURCE OUTPUT LEVEL TARGET_MODE)
    if(NOT DEFINED ${required})
        message(FATAL_ERROR "${required} is required")
    endif()
endforeach()
if(NOT LEVEL MATCHES "^O[02]$" OR NOT TARGET_MODE MATCHES "^(host|elf|r3000|allegrex|n64)$")
    message(FATAL_ERROR "unknown patch-cell level/target")
endif()
file(MAKE_DIRECTORY "${OUTPUT}")
function(checked label)
    execute_process(COMMAND ${ARGN} RESULT_VARIABLE status OUTPUT_VARIABLE out ERROR_VARIABLE err)
    if(NOT status EQUAL 0)
        message(FATAL_ERROR "${label} failed (${status})\n${out}\n${err}")
    endif()
endfunction()

# One cell each for the copied/branched/looped/projected/narrow/wide input
# expressions; two for distinct fresh outputs and each generic instantiation.
set(level "${LEVEL}")
set(target "${TARGET_MODE}")
set(flags -${level} -fno-eval-calls)
if(target STREQUAL elf)
    list(APPEND flags -target x86_64-unknown-linux-gnu)
elseif(target STREQUAL r3000)
    list(APPEND flags -target mips-unknown-elf -march=r3000 -mabi=o32)
elseif(target STREQUAL allegrex)
    list(APPEND flags -target mipsel-unknown-elf -march=allegrex -mabi=o32)
elseif(target STREQUAL n64)
    list(APPEND flags -mprofile=mips64-n64)
endif()
set(assembly "${OUTPUT}/${level}-${target}.s")
checked("${level}/${target}" "${CC}" -S ${flags} "${SOURCE}" -o "${assembly}")
file(READ "${assembly}" text)
string(REGEX MATCHALL "[.]Lcross[.]patch[.]value[.][0-9]+[.]end:" fields "${text}")
list(LENGTH fields count)
list(REMOVE_DUPLICATES fields)
list(LENGTH fields unique)
if(NOT count EQUAL 14 OR NOT unique EQUAL count)
    message(FATAL_ERROR "${level}/${target}: expected 14 distinct cells, found ${count}/${unique}")
endif()
